### ISSUE TITLE
Phrase Concept

### ISSUE THREAD

**Issue by JunsFu** [sunlicai/EMT-DLFR#1]
First of all thank you for your hard work!
I would like to ask a question, what characteristics do the low-level features and high-level features mentioned in the article correspond to?
My understanding is:
Low-level features = features of the original data
Advanced features = features processed by neural networks
I don’t know if my understanding is wrong.

**Comment by youcaiSUN** [comment]
Hi, thanks for your interest in our work!

You understanding is correct!
