### ISSUE TITLE
Have  a question

### ISSUE THREAD

**Issue by Ma-PC** [sunlicai/EMT-DLFR#2]
Hello, thank you for your contribution to the article, I read your article benefited a lot, but I am a novice, there is a place not quite understand.

The dimension of module G in this paper is 3×d, which is inconsistent with the shape and size of Hm. May I ask how formula 8 works?

**Comment by sunlicai** [comment]
Hi, 
Thanks for your interest in our work! The core cross-attention module in MPU can take two unaligned (i.e., different temporal dimensions)  sequences as inputs. Here, the global multimodal context $G \in \mathcal{R}^{3 \times d}$ and local unimodal features $H_m \in \mathcal{R}^{T_m \times d}$. Although $3 \neq T_m$, the cross-attention module can achieve this by calculating the dot-product attention shown in Equation 3. The attention map has the dimension of $\mathcal{R}^{3 \times T_m}$ or $\mathcal{R}^{T_m \times 3}$, which captures the interactions between $G$ and $H_m$.

**Comment by Ma-PC** [comment]
As a novice to get your answer, thank you very much !!!

**Comment by Ma-PC** [comment]
As a novice to get your answer, thank you very much !!!
